import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from 'next/font/local';
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

const dana = localFont({src: '../public/fonts/dana-font/dana regular.ttf'})

export const metadata: Metadata = {
  title: "Customed Ecommerce",
  description: "generated by might",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl">
      <body className={`${inter.className} ${dana.className}`}>{children}</body>
    </html>
  );
}
