import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "@/components/Navbar";
import ToasterProvider from "./provider/ToasterProvider";

const dana = localFont({ src: "../public/fonts/dana-font/dana regular.ttf" });

export const metadata: Metadata = {
  title: "Customed Ecommerce",
  description: "generated by might",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>      
      <ClerkProvider>
    <html>
        <body className={` ${dana.className}`}>
          <ToasterProvider />
          <Navbar />
          {children}
        </body>
    </html>
      </ClerkProvider>
    </>

  );
}
